### ISSUE TITLE
add license file so we can ship on conda

### ISSUE THREAD

**Issue by beckermr** [esheldon/desimage#1]
This code appears mature enough that putting stuff in conda would be good. Just needs the GPL.

**Comment by esheldon** [comment]
It already has a license file, do you mean something else?

**Comment by esheldon** [comment]
OH, sorry, misread this as `desmeds`

**Comment by esheldon** [comment]
done

**Comment by esheldon** [comment]
Note there is some non-generic code that gets installed such as `des-make-image-batch` for generating batch files for wq etc.

**Comment by esheldon** [comment]
I tagged 0.9.0

**Comment by beckermr** [comment]
We'll want setuptools but I can patch that in the feedstock for now.
